services:
  tf-jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
